server:
  port: 8080
spring:
  application:
    name: student
  datasource:
    url: jdbc:mysql://localhost:3306/microservices?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
logging:
  level:
    root: info

resilience4j:
  circuitbreaker:
    instances:
      addStudentCircuitBreaker:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s